### ISSUE TITLE
Conversion issue unicode to ascii

### ISSUE THREAD

**Issue by sasurajachar** [aravindavk/ascii2unicode#12]
ಜ್ಞಾಪಕ is not converted properly﻿.. its converted as  ಜ್ಞಾ¥ÀPÀ  instead of eÁÕ¥ÀPÀ

**Comment by aravindavk** [comment]
https://aravindavk.in/sanka ಇದರಲ್ಲಿ ಈ ತೊಂದರೆ ಸರಿಪಡಿಸಲಾಗಿದೆ. ನೋಡಿ ಇನ್ನೂ ಏನಾದರೂ ತೊಂದರೆಗಳಿದ್ದರೆ ತಿಳಿಸಿ
