### ISSUE TITLE
avagraha (s) is not converted properly

### ISSUE THREAD

**Issue by mithungn** [aravindavk/ascii2unicode#14]
£ÀªÉÆÃ„¸ÀÄÛvÉÃ when converted should be ನಮೋ**ಽ**ಸ್ತುತೇ

Instead, in this converter it converts to ನಮೋಸ್ತುತೇ

**Comment by aravindavk** [comment]
https://aravindavk.in/sanka ಇದರಲ್ಲಿ ಈ ತೊಂದರೆ ಸರಿಪಡಿಸಲಾಗಿದೆ. ನೋಡಿ ಇನ್ನೂ ಏನಾದರೂ ತೊಂದರೆಗಳಿದ್ದರೆ ತಿಳಿಸಿ
