### ISSUE TITLE
nudi font set download link ...

### ISSUE THREAD

**Issue by aiamuzz** [aravindavk/ascii2unicode#15]
Hello @aravindavk ...

can you please point me to the download link to the nudi font set ... i believe these fonts are opensource ... i can't seem to locate it as the websites mentioning it are kannada language sites and reading through them is hard for me ... i have some document which use **`nudi 01 e`** font 

thanks.

**Comment by aravindavk** [comment]
I don't have any other links other than the below one 

http://www.kagapa.in/kannada/sites/default/files/downloads/Nudi-5.0/Fonts.zip
