### ISSUE TITLE
ಪ್ರೊ ascii to unicode have issue

### ISSUE THREAD

**Issue by xaisng** [aravindavk/ascii2unicode#2]
Ascii :- 
(J) ªÀÄÆgÀÄ ¥ÉÇæmÁ£ïUÀ¼ÀÄ  

Unicode : 
(ಎ) ಮೂರು ಪೆÇ್ರಟಾನ್‍ಗಳು   

Its should be 
ಪ್ರೊಟಾನ್‍ಗಳು

**Comment by aravindavk** [comment]
https://aravindavk.in/sanka ಇದರಲ್ಲಿ ಈ ತೊಂದರೆ ಸರಿಪಡಿಸಲಾಗಿದೆ. ನೋಡಿ ಇನ್ನೂ ಏನಾದರೂ ತೊಂದರೆಗಳಿದ್ದರೆ ತಿಳಿಸಿ
