### ISSUE TITLE
conversion issue1

### ISSUE THREAD

**Issue by MayuraVerma** [aravindavk/ascii2unicode#4]
¨sÁμÉ¬ÄAzÀ

should be ಭಾಷೆಯಿಂದ 

it is converting to 
ಭಾμÉಯಿಂದ
Here "μÉ" is not converted. Although it is listed in the mapping.

    "µÉ": "ಷೆ",
    "µË": "ಷೌ",

But interestingly, when I search for "μÉ" in chrome inside the nudi.py, both  "µÉ" and "µË" gets highlighted.

Please check.

**Comment by MayuraVerma** [comment]
I found the root cause and solution. 
There are two similar looking ascii, greek letter mu and micro. Some softwares they are interchangable and some softwares chooses one over another.
https://en.wiktionary.org/wiki/%CE%BC

So, along with 
along with these below.
    "µï": "ಷ್",
    "µÀ": "ಷ",
    "µÁ": "ಷಾ",
    "µÉ": "ಷೆ",
    "µË": "ಷೌ"
we need to add 
    "μï": "ಷ್",
    "μÀ": "ಷ",
    "μÁ": "ಷಾ",
    "μÉ": "ಷೆ",
    "μË": "ಷೌ"

for both variations to work.

Please add it.

**Comment by aravindavk** [comment]
Thanks for the details. 

https://aravindavk.in/sanka ಇದರಲ್ಲಿ ಈ ತೊಂದರೆ ಸರಿಪಡಿಸಲಾಗಿದೆ. ನೋಡಿ ಇನ್ನೂ ಏನಾದರೂ ತೊಂದರೆಗಳಿದ್ದರೆ ತಿಳಿಸಿ
